### ISSUE TITLE
Execute functioning version procedure script with C#

### ISSUE THREAD

**Issue by futurify-ydang** [nearform/temporal_tables#15]
Hi guys,

I'm trying to run the **versioning_function.sql** with C# at start up time to create procedure but seems that can not run.
I removed the comment statements in script.
I read file **versioning_function.sql** into string and then use **ExecuteSqlCommand** to execute script. It thrown an exception 
`"Input string was not in a correct format."`

Stack trace
````
{System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RawSqlCommandBuilder.Build(String sql, IEnumerable`1 parameters)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, Object[] parameters)
   at BSWeb.Startup._updateDatabase(String rootPath, DbContext context) in Startup.cs:line 449}
`````
Please give me an idea. Thanks!

**Comment by twinmind** [comment]
This error is specific to C# and thrown by `StringBuilder. AppendFormat` method and it is not related to any issue with this function. You might need to escape all characters like `{`, `}`, `$` in procedure source code to be able to pass it into C# string formatting method.

**Comment by futurify-ydang** [comment]
Thanks @twinmind  i have to create a sqlcommand then execute sql query.
